### ISSUE TITLE
m119

### ISSUE THREAD

**Issue by prophetmaster** [RichCattell/Marlin#19]
hello, I have a problem with your firmware when I send a signal M119 z-probe returns me always open yet so I plug zmax it works. Is this a bug, or is it that I am doing something wrong?

**Comment by RichCattell** [comment]
Which build are you using master or development ?
I am currently making some changes the development branch and so I might not work correctly at the moment..

**Comment by RichCattell** [comment]
Which build are you using master or development ?
I am currently making some changes to the development branch and so It might not work correctly at the moment..
I am planning to release a new test build soon once I have the bugs fixed in development..

**Comment by prophetmaster** [comment]
development

**Comment by prophetmaster** [comment]
i have tested in master branch all of the endstop work :-)
