### ISSUE TITLE
M666

### ISSUE THREAD

**Issue by prophetmaster** [RichCattell/Marlin#20]
I have one issue with this function if you send : 

M666 P X... Y... Z...

X and Y work Z return to 0.

In master branch

**Comment by RichCattell** [comment]
In the master branch version the m666 p function doesn't work like this.. it only changes the z parameter for the probe:

M666 P-5.5

Will set the z-probe's Z offset parameter to -5.5mm

If you specify values for x y and z these will change the end stop offset values.

In my development branch (and test version that will be available soon this function does work as you described)

**Comment by prophetmaster** [comment]
thank you for clarifying that it is true that I have not tried it just with a M666 P-5.5
