### ISSUE TITLE
M503 does not report new U, V, W parameters

### ISSUE THREAD

**Issue by WZ9V** [RichCattell/Marlin#25]
M666 L was updated with U, V, W reporting, but M503 does not report them at this time.

**Comment by RichCattell** [comment]
Fixed in commit #28

**Comment by WZ9V** [comment]
This one was a bit different than the EEPROM one.  M503 is not printing the values at all when it dumps the status.

**Comment by WZ9V** [comment]
My mistake missed the updated values.  Looks good.
