### ISSUE TITLE
M666 U, V, W not surviving a reset

### ISSUE THREAD

**Issue by WZ9V** [RichCattell/Marlin#26]
I do the following and the U, V, W values are wiped out or appear to be.
M666 U1 V2 W3
M500
M666 L  // U = 1, V = 2, W = 3
Reset printer 
M666 L   // U, V, W now all 0

Log from Pronterface

> > > m666 u-1 v-2 w-3
> > > SENDING:M666 U-1 V-2 W-3
> > > m666 l
> > > SENDING:M666 L
> > > Current Delta geometry values:
> > > X (Endstop Adj): -1.663
> > > Y (Endstop Adj): -0.613
> > > Z (Endstop Adj): -1.675
> > > P (Z-Probe Offset): X0.00 Y0.00 Z0.10
> > > A (Tower A Position Correction): 0.000
> > > B (Tower B Position Correction): 0.000
> > > C (Tower C Position Correction): 0.448
> > > I (Tower A Radius Correction): 0.000
> > > J (Tower B Radius Correction): 0.000
> > > K (Tower C Radius Correction): -0.241
> > > U (Tower A Diagional Rod Correction): -1.000
> > > V (Tower B Diagonal Rod Correction): -2.000
> > > W (Tower C Diagonal Rod Correction): -3.000
> > > R (Delta Radius): 182.21
> > > D (Diagonal Rod Length): 287.10
> > > H (Z-Height): 256.83
> > > m500
> > > SENDING:M500
> > > echo:Settings Stored
> > > Reset.
> > > start
> > > echo: External Reset
> > > Marlin RC Testing 2015-01-26
> > > echo: Last Updated: Jan 26 2015 21:19:28 | Author: (David Fruehwald, Ultibots K250VS)
> > > Compiled: Jan 26 2015
> > > echo: Free Memory: 1677  PlannerBufferBytes: 1232
> > > echo:Stored settings retrieved
> > > echo:Steps per unit:
> > > echo:  M92 X80.00 Y80.00 Z80.00 E820.00
> > > echo:Maximum feedrates (mm/s):
> > > echo:  M203 X200.00 Y200.00 Z200.00 E200.00
> > > echo:Maximum Acceleration (mm/s2):
> > > echo:  M201 X4500 Y4500 Z4500 E4500
> > > echo:Acceleration: S=acceleration, T=retract acceleration
> > > echo:  M204 S1000.00 T3000.00
> > > echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
> > > echo:  M205 S0.00 T0.00 B20000 X2.00 Z2.00 E5.00
> > > echo:Home offset (mm):
> > > echo:  M206 X0.00 Y0.00 Z0.00
> > > echo:Delta Geometry adjustment:
> > > echo:  M666 A0.000 B0.000 C0.448 I0.000 J0.000 K-0.241 R182.21 D287.10 H256.83
> > > echo:Endstop Offsets:
> > > echo:  M666 X-1.66 Y-0.61 Z-1.67
> > > echo:Z-Probe Offset:
> > > echo:  M666 P X0.00 Y0.00 Z0.10
> > > echo:PID settings:
> > > echo:   M301 P18.62 I1.37 D63.14
> > > echo:SD card ok
> > > m666 l
> > > SENDING:M666 L
> > > Current Delta geometry values:
> > > X (Endstop Adj): -1.663
> > > Y (Endstop Adj): -0.613
> > > Z (Endstop Adj): -1.675
> > > P (Z-Probe Offset): X0.00 Y0.00 Z0.10
> > > A (Tower A Position Correction): 0.000
> > > B (Tower B Position Correction): 0.000
> > > C (Tower C Position Correction): 0.448
> > > I (Tower A Radius Correction): 0.000
> > > J (Tower B Radius Correction): 0.000
> > > K (Tower C Radius Correction): -0.241
> > > U (Tower A Diagional Rod Correction): 0.000
> > > V (Tower B Diagonal Rod Correction): 0.000
> > > W (Tower C Diagonal Rod Correction): 0.000
> > > R (Delta Radius): 182.21
> > > D (Diagonal Rod Length): 287.10
> > > H (Z-Height): 256.83

**Comment by RichCattell** [comment]
Fixed in commit #28
