### ISSUE TITLE
compiled error if uncomment the line #577/584/585 Servo_endstops items 

### ISSUE THREAD

**Issue by Markts99** [RichCattell/Marlin#49]
I am using this newest files and would like to measure the Z Endstop offset from the hotend so I enable the three lines of configuration.h; but I got error message and stop the comiling. what should I do? BTW, I disable these three lines tried to measure the offset data, I pull down the hotend above the surface of bed at 0.1mm, then set G92 X0 Y0 Z0, then key in G1 Z10 to try to pull hight Z10mm, I did tried G92 or G91 then but the hotend just went up to more than 15cm height, it wouldn't stop at Z 10mm. What should I change the setting to enable the function?
Regards,
Mark

**Comment by IceflowCW** [comment]
You need only to uncoment the line for the servo you need to use, i assume the Z servo, if using ramps you need to conect it to D11. Then conect the endstop as normal to Z min. Try that way.
