### ISSUE TITLE
Possible bug on G30 A?

### ISSUE THREAD

**Issue by cyberbsd** [RichCattell/Marlin#8]
Hi RichCattell,

On Marlin_main.cpp Line 1619
         if (bed_level_z + endstop_adj[2] < l_endstop) l_endstop = bed_level_x + endstop_adj[2];

Is it a bug? Shouldn't it be  "bed_level_z" ?

Regards,
Clarence

**Comment by braddo99** [comment]
This bug still seems to be in the code but yet there are much more recent commits, I wonder what's up? It could be that a lot of folks are having issues with autocal because of this one.

**Comment by RichCattell** [comment]
Apologies.. i did think that that i had fixed this in the Master branch.. but it appears i hadn't
It has now been added,

**Comment by braddo99** [comment]
That's great Rich, thanks!
